[ha_cluster]
ha-pg-01 ansible_host=51.250.73.53 private_ip=10.1.0.31
ha-pg-02 ansible_host=111.88.145.68 private_ip=10.1.1.23
ha-pg-03 ansible_host=158.160.192.37 private_ip=10.1.2.32

[ha_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
