[postgres]
bench-vm-01 ansible_host=111.88.240.31

[clickhouse]
bench-vm-02 ansible_host=111.88.244.66

[benchmark:children]
postgres
clickhouse

[benchmark:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_become=true

